### ISSUE TITLE
Add support for newer version of template-haskell (>= 2.18.0.0)

### ISSUE THREAD

**Issue by quyumkehinde** [akshaymankar/polysemy-mocks#7]
I got this error while trying to compile the package, version 0.3.0.0.
![image](https://user-images.githubusercontent.com/49095691/209737295-0bb8e008-35e6-4cb5-96e6-7988d954cf3e.png)
After some debugging, I found out that the error was due to the fact that the type of the `Conp` data constructor from the template-haskell package have changed from being `ConP Name [Pat]` ([reference](https://hackage.haskell.org/package/template-haskell-2.17.0.0/docs/Language-Haskell-TH.html#t:Pat)) to `ConP Name [Type] [Pat]` ([reference](https://hackage.haskell.org/package/template-haskell-2.18.0.0/docs/Language-Haskell-TH.html#t:Pat)) in all the versions >= 2.18.0.0.

Could you please look into this? I'm happy to make a PR to fix this, so please let me know if you'd be open to that.

Thank you.

**Comment by akshaymankar** [comment]
Thanks for reporting this @quyumkehinde! Please feel free to send a PR :smile:

**Comment by quyumkehinde** [comment]
@akshaymankar please check out the PR [here](https://github.com/akshaymankar/polysemy-mocks/pull/8)

**Comment by quyumkehinde** [comment]
@akshaymankar any chance the updated code will be uploaded to Hackage anytime soon? :)

**Comment by akshaymankar** [comment]
Yes, I will update the CI to ensure tests happen with GHC 9.2 and 9.4. If all goes well, this should soon be on hackage soon :)

**Comment by akshaymankar** [comment]
@quyumkehinde I've published version [0.3.1.0](https://hackage.haskell.org/package/polysemy-mocks-0.3.1.0). Thanks again for noticing and fixing the issue :rocket:
